# lista de musicas
# será retornado ao index.py um dos indices da lista

a = [
    "Seu amor me pegou",
    "Essa é minha vida, olha a pirâmide lá",
    "Tell me why",
    "Caneta azul, azul caneta",
    "O que pensa que eu sou, se não sou o que pensou, me libera",
    "Eu pensei que era uma joia rara, era bijuteria",
    "Não me jogue pedras, mas sim beijos beijos",
    "Leticia, onde você vai com esse mototaxista",
    "É só você me ligar aaaaaaaa",
    "Desejo a toda inimigas vida longa",
    "Sou faraó ÓóÓóÓóÓóÓ",
    "Baby shark tututututuu",
    "Não tinha medo o tal João de Santo Cristo ",
    "To com fome, quero leite",
    "Foguete do tipo nasa saindo da atmosfera",
    "Beija minha boca, desvenda meus misterios",
    "Quem não tem teto de vidro que atire a primeira pedra",
    "Entra na minha casa, entra na minha vida",
    "O preço que se paga as vezes é alto de mais",
    "Deixa eu bagunçar você",
    "Sempre em frente foi o conselho que ela me deu",
    "Pensei que era liberdade, mas na verdade era só solidão",
    "Devendo a vida a si mesmo pra nunca pagar",
    "Na falta de poesia, hoje sou trovão",
    "Every breath leaves me one less to my last",
    "Peludin din din Peludão dão dão Meu cãozinho zinho zinho",
    "Se você não sabe contra quem lutar só vai ter inimigos em todo lugar",
    "Vi quase tudo que queria ver, só não vi você",
    "Não te dizer o que eu penso ja é pensar em dizer",
    "Mas tudo tem uma hora certa pra mudar",
    "Cansei de buscar respostas",
    "Que lado você vai escolher? Isso é muito mais importante que vencer",
    "Qual é o tamanho da sua fé? Será que é o bastante pra manter você de pé?",
    "Se o mundo la fora quer te apunhalar, lembre que seu corpo é só poeira estelar",
    "Quem é esse ser que pilota os cometas?",
    "Quem era você até me encontrar?",
    "Te dizer que amor não senti, é mentir pra mim",
    "Na sua casa eu nunca mais entrei mas decorei com exatidão todas as coisas como eu deixei",
    "Tudo que eu posso oferecer são minhas palavras pra você",
    "Tudo que eu quero te dizer eu ja cansei de escrever",
    "Jacarezinho, avião, cuidado com o disco voador",
    "Quero que a estrada venha sempre até você e que o vento esteja sempre ao seu favor",
    "Amanhã ou depois, tanto faz se depois for nunca mais",
    "Te vejo sonhando e isso da medo, perdido num mundo que não da pra entrar",
    "Eu estava aqui o tempo todo, só você não viu",
    "Eu vivo sem saber até quando ainda estou vivo, sem saber o calibre do perigo",
    "Eu posso estar sozinho mas eu sei muito bem aonde estou",
    "Mas penso e sigo em frente pra nunca mais viver assim",
    "Aonde quer que eu vá, levo você no olhar",
    "Se alguém ja te deu a mão e não pediu mais nada em troca, pense bem poiss é um dia especial",
    "Foi pouco tempo mas valeu, vivi cada segundo",
    "Te peço pra lembrar que o dia nasce e acaba",
    "Olhe sempre pros dois lados antes de julgar, de se manifestar ou pra cruzar a rua",
    "Eu sou uma contradição e foge da minha mão fazer com que tudo que eu digo faça algum sentido",
    "Fada, fada querida, dona da minha vida",
    "Talvez esteja em Jaraguá, Joinville ou Blumenau, Lá por Santa Catarina"
    
]

