[tool.poetry]
name = "botlive"
version = "0.1.0"
description = "Bot da live"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
twitchio = "~1.2.3"

[tool.poetry.dev-dependencies]
flake8 = "^3.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
botlive = "botlive.bot:run"
